#!/bin/bash

linkList() {
 case $1 in 
	 -a)
			
			;;		 
		*)		 
			read -rp 'Provide link list title : ' linkListTitle
			read -rp 'How many links should be saved? : '	linkCount

			declare -a linkTitle=()
			declare -a linkURL=()

			echo -e "\n"

			for linkData in $( seq 1 $linkCount ); 
			do 
				read -rp "Provide the title of link number $linkData : " title 
				read -rp "Provide the URL of link number $linkData : "	url
				linkTitle+=("$title")
				linkURL+=("$url")
				echo -e "\n"
			done;	

			touch "$linkListTitle.md"
			echo -e "# $linkListTitle\n\n___" >> "$linkListTitle.md"

			linkNumber=$((linkCount-1))

			for number in $(seq 0 $linkNumber); 
			do	
				echo -e "[${linkTitle[$number]}][$((number + 1))]\n" >> "$linkListTitle.md"
			done;

			echo -e "___" >> "$linkListTitle.md"
			
			for number in $(seq 0 $linkNumber); 
			do	
				echo -e "[$((number + 1))]:${linkURL[$number]}" >> "$linkListTitle.md"
			done;

			echo -e "\nLink List Complete \n" | lolcat
#			vim "$linkListTitle.md"

			exit
			;;	
	esac
	exit
}

linkList "$1" "$2" 
